增加日报提醒功能，在工作日  提醒发日报周报月报提醒
lich0821/WeChatRobot pull request #16
Opened 2023-10-01 13:56 UTC by NoobHumiliator

使用chinese_calendar判断是否工作日 符合国情。
写了几个复杂的日期判断，手机日历APP无法实现。

2023-10-01 14:10 UTC, lich0821 requested changes
感谢 PR，蛮有意思的功能！

2023-10-01 14:10 UTC, lich0821 commented on report_reminder.py
> +        #日报周报月报提醒
这个注释跟其他不一样，少了个空格哈，可以用 autopep8 格式化一下（行宽 120）

2023-10-01 14:10 UTC, lich0821 commented on main.py
>  def main():
这里删除了一个空行，方法之间2个空行比较统一。

2023-10-01 14:10 UTC, lich0821 commented on report_reminder.py
这个文件，建议命名为 `func_xxxx`，因为这些功能“插件”越来越多，后续我计划将他们单独挪到一个文件夹里。

2023-10-02 08:34 UTC, NoobHumiliator commented
作者您好 上述问题已按意见修改。
很喜欢这个项目，后面我关于新feature的想法会提到issue里面大家讨论，如果觉得有意思的功能，我会尝试做出来加进项目。
对Python不是很熟。 感谢指点谢谢。

2023-10-02 09:58 UTC, lich0821 approved these changes
LGTM

2023-10-02 09:58 UTC, merged

2023-10-02 09:58 UTC, lich0821 commented
> 作者您好 上述问题已按意见修改。 很喜欢这个项目，后面我关于新feature的想法会提到issue里面大家讨论，如果觉得有意思的功能，我会尝试做出来加进项目。 对Python不是很熟。 感谢指点谢谢。

期待！