chatglm3接入，可实现函数调用，代码执行等功能
lich0821/WeChatRobot pull request #19
Opened 2023-11-12 06:02 UTC by yanlang0123

集成了chatglm3 6b模型接口，可以本地部署，里面包含函数调用，python代码执行功能。
发送 #帮助 可查看功能信息，其中包含：
本助手有三种模式，#聊天模式 = #1，#工具模式 = #2，#代码模式 = #3。可用发送#对应模式 或者 #编号 进行切换

2023-11-12 08:23 UTC, yanlang0123 commented
漏了个文件

2023-11-12 15:34 UTC, lich0821 requested changes
感谢 PR！功能很丰富也很实用。我提几个小建议哈：
1、建议使用autopep8对代码格式化一下（行宽设置为120），保持风格统一；
2、`tool`命名可能会让人困惑，建议直接使用`func_chatglm`封装一个包，方便使用；
3、建议将`wcf`从`ChatGLM`中解耦出来（参考`func_chatgpt.py`、`func_tigerbot.py`等），以便不使用`wcf`框架的项目也能方便地把`ChatGLM`单独拿出去用。
4、建议在`func_chatglm`包内增加一个`README`，简述如何本地部署或者提供个教程链接。

2023-11-12 15:34 UTC, lich0821 commented on func_chatglm.py
> +
把像这些这样的行末空白都去一下吧

2023-11-12 15:34 UTC, lich0821 commented on func_chatglm.py
> +
行末空白

2023-11-12 15:34 UTC, lich0821 commented on tool/comfyUI_api.py
> +import websocket #NOTE: websocket-client (https://github.com/websocket-client/websocket-client)
文件依赖了 `websocket`，把它添加到`requirements.txt`里

2023-11-12 15:34 UTC, lich0821 commented on tool/code_kernel.py
> +from PIL import Image
把`pillow`添加到`requirements.txt`里

2023-11-12 15:34 UTC, lich0821 commented on tool/code_kernel.py
> +import jupyter_client
把`jupyter_client`添加到`requirements.txt`里

2023-11-12 15:34 UTC, lich0821 commented on tool/code_kernel.py
> +def execute(code, kernel: CodeKernel) -> tuple[str, str | Image.Image]:
`|`是3.10的新特性，建议使用`tuple[str, Union[str, Image.Image]]`以提高版本兼容性。

2023-11-12 15:34 UTC, lich0821 commented on tool/code_kernel.py
> +    def get_error_msg(self, msg, verbose=False) -> str | None:
`|`是3.10的新特性，建议使用`Optional[str]`以提高版本兼容性

2023-11-12 15:34 UTC, lich0821 commented on func_chatglm.py
> +    chat = ChatGLM(key, api, proxy, prompt)
这里实例化应该会出错，参数对不上，建议把`wcf`解耦。

2023-11-13 06:54 UTC, yanlang0123 commented
感谢提的建议和问题，这边基本都做了优化调整，修改

2023-11-13 07:26 UTC, lich0821 commented on chatglm/README.MD
> +ipython kernel install --name chatglm3 --user
这个依赖 `ipykernel `，需要在 `requirements.txt`里添加一下。
一般，建议创建一个新虚拟环境，然后`pip install -r requirments.txt`安装依赖，然后运行项目，看能不能顺利跑起来。如果有依赖缺失，就很容易发现。

2023-11-13 08:01 UTC, lich0821 reviewed
感谢修改！
另外，建议重新排列一下import（如果使用 VSCode的话，`Ctrl+Shift+P`唤出控制面板，输入`Organize Imports`），看起来会舒服好多。

2023-11-15 13:24 UTC, yanlang0123 commented
[重新排列一下import，添加 ipykernel依赖]

2023-11-16 01:07 UTC, lich0821 approved these changes

2023-11-16 01:09 UTC, lich0821 approved these changes
合并～

2023-11-16 01:09 UTC, merged