适配智谱
lich0821/WeChatRobot pull request #49
Opened 2024-02-19 14:28 UTC by yudong521

2024-02-19 14:31 UTC, lich0821 approved these changes
666，麻烦添加一下依赖吧，方便用户

2024-02-19 14:33 UTC, lich0821 requested changes

2024-02-19 14:33 UTC, lich0821 commented on base/func_zhipu.py
> +from zhipuai import ZhipuAI
把这俩依赖添加到 `requirements.txt` 里吧

2024-02-20 04:40 UTC, yudong521 commented
已经修改添加啦

2024-02-20 06:48 UTC, merged